"""initial_schema

Revision ID: 9f44ad20e934
Revises: 
Create Date: 2026-09-30 14:58:47.531935

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '9f44ad20e934'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farmers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('village_code', sa.String(), nullable=True),
    sa.Column('district_code', sa.String(), nullable=True),
    sa.Column('total_land_ha', sa.Float(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmers_id'), 'farmers', ['id'], unique=False)
    op.create_table('schemes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('benefit_score', sa.Integer(), nullable=False),
    sa.Column('domain', sa.String(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_schemes_code'), 'schemes', ['code'], unique=True)
    op.create_index(op.f('ix_schemes_id'), 'schemes', ['id'], unique=False)
    op.create_table('source_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_row_id', sa.String(), nullable=False),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('loaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_records_id'), 'source_records', ['id'], unique=False)
    op.create_index(op.f('ix_source_records_source_name'), 'source_records', ['source_name'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('entity', sa.String(), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_id'), 'audit_log', ['id'], unique=False)
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('clean_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_record_id', sa.Integer(), nullable=False),
    sa.Column('name_norm', sa.String(), nullable=True),
    sa.Column('father_norm', sa.String(), nullable=True),
    sa.Column('name_phonetic', sa.String(), nullable=True),
    sa.Column('mobile10', sa.String(), nullable=True),
    sa.Column('village_code', sa.String(), nullable=True),
    sa.Column('district_code', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('survey_no', sa.String(), nullable=True),
    sa.Column('bank_last4', sa.String(), nullable=True),
    sa.Column('land_ha', sa.Float(), nullable=True),
    sa.Column('crop', sa.String(), nullable=True),
    sa.Column('season', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_clean_records_dist_phone', 'clean_records', ['district_code', 'name_phonetic'], unique=False)
    op.create_index(op.f('ix_clean_records_id'), 'clean_records', ['id'], unique=False)
    op.create_index('ix_clean_records_mobile10', 'clean_records', ['mobile10'], unique=False)
    op.create_index('ix_clean_records_vill_surv', 'clean_records', ['village_code', 'survey_no'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.String(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('source_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.ForeignKeyConstraint(['source_record_id'], ['source_records.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enrollments_farmer_id'), 'enrollments', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_enrollments_id'), 'enrollments', ['id'], unique=False)
    op.create_table('farmer_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(), nullable=True),
    sa.Column('father_name', sa.String(), nullable=True),
    sa.Column('dob', sa.String(), nullable=True),
    sa.Column('gender', sa.String(), nullable=True),
    sa.Column('mobile', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('village', sa.String(), nullable=True),
    sa.Column('taluka', sa.String(), nullable=True),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('pincode', sa.String(), nullable=True),
    sa.Column('total_land_ha', sa.Float(), nullable=True),
    sa.Column('ownership_type', sa.String(), nullable=True),
    sa.Column('main_crops', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('irrigation_type', sa.String(), nullable=True),
    sa.Column('interests', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('agristack_id', sa.String(), nullable=True),
    sa.Column('bank_name', sa.String(), nullable=True),
    sa.Column('ifsc', sa.String(), nullable=True),
    sa.Column('email_opt_in', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('completeness', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_index(op.f('ix_farmer_profiles_id'), 'farmer_profiles', ['id'], unique=False)
    op.create_table('flags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('reason', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_flags_farmer_id'), 'flags', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_flags_id'), 'flags', ['id'], unique=False)
    op.create_index('ix_flags_status_type', 'flags', ['status', 'type'], unique=False)
    op.create_table('land_parcels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('village_code', sa.String(), nullable=False),
    sa.Column('survey_no', sa.String(), nullable=False),
    sa.Column('area_ha', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_land_parcels_farmer_id'), 'land_parcels', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_land_parcels_id'), 'land_parcels', ['id'], unique=False)
    op.create_table('recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('eligible', sa.Boolean(), nullable=False),
    sa.Column('reasons_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('already_enrolled', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_farmer_id'), 'recommendations', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_table('email_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_email_log_id'), 'email_log', ['id'], unique=False)
    op.create_table('farmer_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_id', sa.Integer(), nullable=False),
    sa.Column('clean_record_id', sa.Integer(), nullable=False),
    sa.Column('method', sa.String(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['clean_record_id'], ['clean_records.id'], ),
    sa.ForeignKeyConstraint(['farmer_id'], ['farmers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farmer_links_farmer_id'), 'farmer_links', ['farmer_id'], unique=False)
    op.create_index(op.f('ix_farmer_links_id'), 'farmer_links', ['id'], unique=False)
    op.create_table('match_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_a', sa.Integer(), nullable=False),
    sa.Column('record_b', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('features_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['record_a'], ['clean_records.id'], ),
    sa.ForeignKeyConstraint(['record_b'], ['clean_records.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_candidates_id'), 'match_candidates', ['id'], unique=False)
    op.create_table('scheme_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('farmer_profile_id', sa.Integer(), nullable=False),
    sa.Column('scheme_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('form_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('autofilled_keys', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('officer_note', sa.String(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['farmer_profile_id'], ['farmer_profiles.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['scheme_id'], ['schemes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_scheme_applications_id'), 'scheme_applications', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_scheme_applications_id'), table_name='scheme_applications')
    op.drop_table('scheme_applications')
    op.drop_index(op.f('ix_match_candidates_id'), table_name='match_candidates')
    op.drop_table('match_candidates')
    op.drop_index(op.f('ix_farmer_links_id'), table_name='farmer_links')
    op.drop_index(op.f('ix_farmer_links_farmer_id'), table_name='farmer_links')
    op.drop_table('farmer_links')
    op.drop_index(op.f('ix_email_log_id'), table_name='email_log')
    op.drop_table('email_log')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_farmer_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_index(op.f('ix_land_parcels_id'), table_name='land_parcels')
    op.drop_index(op.f('ix_land_parcels_farmer_id'), table_name='land_parcels')
    op.drop_table('land_parcels')
    op.drop_index('ix_flags_status_type', table_name='flags')
    op.drop_index(op.f('ix_flags_id'), table_name='flags')
    op.drop_index(op.f('ix_flags_farmer_id'), table_name='flags')
    op.drop_table('flags')
    op.drop_index(op.f('ix_farmer_profiles_id'), table_name='farmer_profiles')
    op.drop_table('farmer_profiles')
    op.drop_index(op.f('ix_enrollments_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_farmer_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index('ix_clean_records_vill_surv', table_name='clean_records')
    op.drop_index('ix_clean_records_mobile10', table_name='clean_records')
    op.drop_index(op.f('ix_clean_records_id'), table_name='clean_records')
    op.drop_index('ix_clean_records_dist_phone', table_name='clean_records')
    op.drop_table('clean_records')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_index(op.f('ix_audit_log_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_source_records_source_name'), table_name='source_records')
    op.drop_index(op.f('ix_source_records_id'), table_name='source_records')
    op.drop_table('source_records')
    op.drop_index(op.f('ix_schemes_id'), table_name='schemes')
    op.drop_index(op.f('ix_schemes_code'), table_name='schemes')
    op.drop_table('schemes')
    op.drop_index(op.f('ix_farmers_id'), table_name='farmers')
    op.drop_table('farmers')
    # ### end Alembic commands ###
